name: Build and Push Docker image to Docker Hub

on:
  release:
    types: [published]
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get tag name
        id: get_tag_name
        run: echo "Tag name: ${{ github.event.release.tag_name }}"
        run: echo "Ref: ${{ github.ref }}"

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: "juanes2499/api-graphql-caching:${{ github.event.release.tag_name }}"